id: P010443
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27417
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་བསྐྱེད་རྫོགས་དམིགས་ཁྲིད་མཁའ་སྤྱོད་འཁྲིད་པའི་ས་མཁན་མཛེས་པར་བྱེད་པའི་རྒྱན
  author: ''
  volumes:
    cc2ec3f689a7479fa8499764f7bb2e6b:
      image_group_id: I4338
      title: ''
      volume_number: 1
      total_pages: 394
      base_file: v001.txt
