id: P010443
initial_creation_type: ocr
source_metadata:
  id: bdr:W27417
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་བསྐྱེད་རྫོགས་དམིགས་ཁྲིད་མཁའ་སྤྱོད་འཁྲིད་པའི་ས་མཁན་མཛེས་པར་བྱེད་པའི་རྒྱན
  author: ''
  volumes: {}
