id: I5A87A4EF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:37:49+00:00'
last_modified: '2022-06-08T13:38:46.864663+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27417
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་བསྐྱེད་རྫོགས་དམིགས་ཁྲིད་མཁའ་སྤྱོད་འཁྲིད་པའི་ས་མཁན་མཛེས་པར་བྱེད་པའི་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9441':
      image_group_id: I4338
      title: ''
      total_pages: 394
      order: 1
      base_file: 9441.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
