id: I5A87A4EF
legacy_id: P010443
ocr_import_info:
  bdrc_scan_id: W27417
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T12:35:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:16:50.762869+00:00'
last_modified: 2022-09-02 15:17:15.268492
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27417
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27417
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེ་བཙུན་རྡོ་རྗེ་རྣལ་འབྱོར་མ་ནཱ་རོ་མཁའ་སྤྱོད་ཀྱི་བསྐྱེད་རྫོགས་དམིགས་ཁྲིད་མཁའ་སྤྱོད་འཁྲིད་པའི་ས་མཁན་མཛེས་པར་བྱེད་པའི་རྒྱན།
  author: གདོང་ཀམ་སྤྲུལ་སྐུ་ངག་དབང་དམ་ཆོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8455024441470333
  ocr_word_median_confidence_index: 0.9300000071525574
quality: null
bases:
  I4338:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4338
      total_pages: 394
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4338.txt
    statistics:
      ocr_word_median_confidence_index: 0.9300000071525574
      ocr_word_mean_confidence_index: 0.8455024441470333
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
